version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - aiohttp
  - astaff
  - ffprobe
  - gdocs
  - HEVC
  - oauthlib
  - pythonic
  - pytube
  - rollup
  - texttospeech
  - unparse
ignoreWords:
  - ffmpeg
  - astaff
import: []
