version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - aiohttp
  - astaff
  - autojunk
  - ffprobe
  - gdocs
  - HEVC
  - lemmatizer
  - oauthlib
  - pythonic
  - pytube
  - rollup
  - senter
  - sents
  - spacy
  - stdev
  - texttospeech
  - unparse
ignoreWords:
  - ffmpeg
  - astaff
import: []
