FROM freespeech:latest

RUN mkdir /root/freespeech/tests
COPY Makefile /root/freespeech
COPY .flake8 /root/freespeech
COPY .mypy.ini /root/freespeech
COPY pyproject.toml /root/freespeech
COPY tests /root/freespeech/tests
RUN pip install -e ".[test]"

ENTRYPOINT ["/bin/bash", "-c"]
