[tool.isort]
profile = "black"

# pyproject.toml
[tool.pytest.ini_options]
filterwarnings = [
    "error",
    'ignore:.*inspect.getargspec.*:DeprecationWarning',
    # note the use of single quote below to denote "raw" strings in TOML
    'ignore:the imp module is deprecated:DeprecationWarning', 
    'ignore:ssl.PROTOCOL_TLS is deprecated:DeprecationWarning',
    'ignore:The distutils package is deprecated and slated for removal in Python 3.12:DeprecationWarning',
    'ignore:unclosed transport <_SelectorSocketTransport:ResourceWarning',
    'ignore:unclosed <socket.socket:ResourceWarning',
    'ignore:unclosed <ssl.SSLSocket',
    # https://github.com/beetbox/audioread/issues/97
    'ignore:unclosed file <_io.BufferedReader:ResourceWarning',
    'ignore:Detected filter using positional arguments.:UserWarning',
]
asyncio_mode = "strict"