[tool.isort]
profile = "black"

# pyproject.toml
[tool.pytest.ini_options]
filterwarnings = [
    "error",
    # note the use of single quote below to denote "raw" strings in TOML
    'ignore:the imp module is deprecated:DeprecationWarning', 
    'ignore:ssl.PROTOCOL_TLS is deprecated:DeprecationWarning',
    'ignore:The distutils package is deprecated and slated for removal in Python 3.12:DeprecationWarning',
]