name: Docker Image CI

on:
  push:
    branches: [ "main", "stable" ]
  pull_request:
    branches: [ "main", "stable" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      AZURE_CONVERSATIONS_TOKEN: ${{ secrets.AZURE_CONVERSATIONS_TOKEN }}
      AZURE_REGION: eastus
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      AZURE_SUBSCRIPTION_KEY: ${{ secrets.AZURE_SUBSCRIPTION_KEY }}
      DEEPGRAM_TOKEN: ${{ secrets.DEEPGRAM_TOKEN }}
      FREESPEECH_STORAGE_BUCKET: freespeech-tests
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      DEEP_L_KEY: ${{ secrets.DEEP_L_KEY }}
      ELEVENLABS_KEY: ${{ secrets.ELEVENLABS_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      # following key is required, but for integration tests it is required to have the
      # externally accessible public endpoint which we don't have in this scenarios
      # so for now setting an arbitrary URL to enable unit-level tests
      TELEGRAM_WEBHOOK_URL: ""
    steps:
    - uses: actions/checkout@v3
    - name: Write Google Application Credentials JSON
      run: |
        mkdir /tmp/id && \
        echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }} | base64 -d - > /tmp/id/test.json
    - name: Docker login
      run: cat /tmp/id/test.json | docker login -u _json_key --password-stdin https://gcr.io
    - name: Build base image
      run: docker build . --file Dockerfile --tag freespeech:latest
    - name: Push to GCR
      run: |
        docker tag freespeech:latest gcr.io/freespeech-343914/freespeech:$GITHUB_SHA && \
        docker push gcr.io/freespeech-343914/freespeech:$GITHUB_SHA
    - name: Build test image
      run: docker build . --file Dockerfile.test --tag freespeech-test:latest
    # - name: Code quality
    #   run: docker run -i freespeech-test:latest "make quality"
    # - name: Type check
    #   run: docker run -i freespeech-test:latest "make typecheck"
    - name: Tests
      env:
        PYTEST_ADDOPTS: "--color=yes"
      run: |
        docker run -i \
        -v /tmp/id/test.json:/id/test.json \
        -e GOOGLE_APPLICATION_CREDENTIALS=/id/test.json \
        -e AZURE_CONVERSATIONS_TOKEN \
        -e AZURE_REGION \
        -e AZURE_STORAGE_CONNECTION_STRING \
        -e AZURE_SUBSCRIPTION_KEY \
        -e DEEPGRAM_TOKEN \
        -e FREESPEECH_STORAGE_BUCKET \
        -e NOTION_TOKEN \
        -e PYTEST_ADDOPTS \
        -e DEEP_L_KEY \
        -e ELEVENLABS_KEY \
        freespeech-test:latest "make test"
