name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Write Google Application Credentials JSON
      run: |
        mkdir /tmp/id && \
        echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }} | base64 -d - > /tmp/id/test.json
    - name: Build base image
      run: docker build . --file Dockerfile --tag freespeech:latest
    - name: Build test image
      run: docker build . --file Dockerfile.test --tag freespeech-test:latest
    - name: Code quality
      run: docker run -i freespeech-test:latest "make quality"
    - name: Type check
      run: docker run -i freespeech-test:latest "make typecheck"
    - name: Tests
      run: |
        docker run -i \
        -v /tmp/id:/id \
        -e GOOGLE_APPLICATION_CREDENTIALS=/id/test.json \
        freespeech-test:latest "make test"
